import '../../data/models/reading_plan_model.dart';

class ReadingPlans {
  static const List<ReadingPlan> all = [
    ReadingPlan(
      id: 'gospels_30',
      title: 'The Gospels in 30 Days',
      description: 'Walk through the life of Jesus in a focused month.',
      chapters: [
        ReadingReference(book: 'Matthew', chapter: 1),
        ReadingReference(book: 'Matthew', chapter: 2),
        ReadingReference(book: 'Matthew', chapter: 3),
        ReadingReference(book: 'Matthew', chapter: 4),
        ReadingReference(book: 'Matthew', chapter: 5),
        ReadingReference(book: 'Matthew', chapter: 6),
        ReadingReference(book: 'Matthew', chapter: 7),
        ReadingReference(book: 'Matthew', chapter: 8),
        ReadingReference(book: 'Matthew', chapter: 9),
        ReadingReference(book: 'Matthew', chapter: 10),
        ReadingReference(book: 'Matthew', chapter: 11),
        ReadingReference(book: 'Matthew', chapter: 12),
        ReadingReference(book: 'Matthew', chapter: 13),
        ReadingReference(book: 'Matthew', chapter: 14),
        ReadingReference(book: 'Matthew', chapter: 15),
        ReadingReference(book: 'Matthew', chapter: 16),
        ReadingReference(book: 'Matthew', chapter: 17),
        ReadingReference(book: 'Matthew', chapter: 18),
        ReadingReference(book: 'Matthew', chapter: 19),
        ReadingReference(book: 'Matthew', chapter: 20),
        ReadingReference(book: 'Matthew', chapter: 21),
        ReadingReference(book: 'Matthew', chapter: 22),
        ReadingReference(book: 'Matthew', chapter: 23),
        ReadingReference(book: 'Matthew', chapter: 24),
        ReadingReference(book: 'Matthew', chapter: 25),
        ReadingReference(book: 'Matthew', chapter: 26),
        ReadingReference(book: 'Matthew', chapter: 27),
        ReadingReference(book: 'Matthew', chapter: 28),
        ReadingReference(book: 'Mark', chapter: 1),
        ReadingReference(book: 'Mark', chapter: 2),
      ],
    ),
    ReadingPlan(
      id: 'john_21',
      title: 'Gospel of John in 21 Days',
      description: 'One chapter a day through John for clarity and depth.',
      chapters: [
        ReadingReference(book: 'John', chapter: 1),
        ReadingReference(book: 'John', chapter: 2),
        ReadingReference(book: 'John', chapter: 3),
        ReadingReference(book: 'John', chapter: 4),
        ReadingReference(book: 'John', chapter: 5),
        ReadingReference(book: 'John', chapter: 6),
        ReadingReference(book: 'John', chapter: 7),
        ReadingReference(book: 'John', chapter: 8),
        ReadingReference(book: 'John', chapter: 9),
        ReadingReference(book: 'John', chapter: 10),
        ReadingReference(book: 'John', chapter: 11),
        ReadingReference(book: 'John', chapter: 12),
        ReadingReference(book: 'John', chapter: 13),
        ReadingReference(book: 'John', chapter: 14),
        ReadingReference(book: 'John', chapter: 15),
        ReadingReference(book: 'John', chapter: 16),
        ReadingReference(book: 'John', chapter: 17),
        ReadingReference(book: 'John', chapter: 18),
        ReadingReference(book: 'John', chapter: 19),
        ReadingReference(book: 'John', chapter: 20),
        ReadingReference(book: 'John', chapter: 21),
      ],
    ),
    ReadingPlan(
      id: 'wisdom_14',
      title: 'Wisdom in 14 Days',
      description: 'A two-week rhythm through Psalms and Proverbs.',
      chapters: [
        ReadingReference(book: 'Psalms', chapter: 1),
        ReadingReference(book: 'Psalms', chapter: 2),
        ReadingReference(book: 'Psalms', chapter: 3),
        ReadingReference(book: 'Psalms', chapter: 4),
        ReadingReference(book: 'Psalms', chapter: 5),
        ReadingReference(book: 'Psalms', chapter: 6),
        ReadingReference(book: 'Psalms', chapter: 7),
        ReadingReference(book: 'Psalms', chapter: 8),
        ReadingReference(book: 'Psalms', chapter: 9),
        ReadingReference(book: 'Psalms', chapter: 10),
        ReadingReference(book: 'Proverbs', chapter: 1),
        ReadingReference(book: 'Proverbs', chapter: 2),
        ReadingReference(book: 'Proverbs', chapter: 3),
        ReadingReference(book: 'Proverbs', chapter: 4),
      ],
    ),
  ];
}
